// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ8eINbyrGjYkQExojHax0_uQVDfkI-C0',
    appId: '1:667520645493:web:42a8aa804a72e1299a3b3c',
    messagingSenderId: '667520645493',
    projectId: 'social-media-app-1d490',
    authDomain: 'social-media-app-1d490.firebaseapp.com',
    storageBucket: 'social-media-app-1d490.appspot.com',
    measurementId: 'G-SMKY4NW9GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA2-DmGCKVhXICcINhACXgywROH7GQg1Q',
    appId: '1:667520645493:android:cf669decbadd606e9a3b3c',
    messagingSenderId: '667520645493',
    projectId: 'social-media-app-1d490',
    storageBucket: 'social-media-app-1d490.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCTGbGgnksZI8zC1WJ5QAiTO2KoK-v9E4',
    appId: '1:667520645493:ios:1a40cd1bdee4a3f49a3b3c',
    messagingSenderId: '667520645493',
    projectId: 'social-media-app-1d490',
    storageBucket: 'social-media-app-1d490.appspot.com',
    iosBundleId: 'com.example.techMedia',
  );
}
